const projects = [
  {
    id: 6,
    title: 'Twitter Clone',
    description: 'This is a Twitter Clone made with T3 Stack. It uses tRPC for the endpoints, Next.JS as the framework as well as Prisma and Tailwind.',
    sourceCodeLink: 'https://github.com/abdul-rehman-d/twitter-clone',
    thumbnail: 'https://raw.githubusercontent.com/abdul-rehman-d/twitter-clone/main/public/screenshot.png',
    livePreviewLink: 'https://twitter.abdulrehmandev.me/',
    technologies: ['TypeScript', 'Nextjs', 'React', 'Tailwind', 'Clerk', 'Postgres', 'Prisma'],
    type: ['featured', 'web-apps'],
  },
  {
    id: 1,
    title: 'URL Shortening API Landing Page',
    description: 'A landing page with a responsive two column layout main section alongside a brand logo header and social icons footer.',
    thumbnail: 'https://github.com/abdul-rehman-d/frontend_mentor_challenges/raw/main/assets/16.jpg',
    sourceCodeLink: 'https://github.com/abdul-rehman-d/frontend_mentor_challenges/tree/main/16_url-shortening-api/',
    livePreviewLink: 'https://abdul-rehman-d.github.io/frontend_mentor_challenges/16_url-shortening-api/',
    technologies: ['HTML', 'CSS', 'Tailwind'],
    type: ['featured', 'ui-implementation'],
  },
  {
    id: 2,
    title: 'Ping Coming Soon Page',
    description: 'A coming soon three section webpage with complete form validation and mobile friendly design.',
    thumbnail: 'https://github.com/abdul-rehman-d/frontend_mentor_challenges/raw/main/assets/14.jpg',
    sourceCodeLink: 'https://github.com/abdul-rehman-d/frontend_mentor_challenges/tree/main/14_ping-coming-soon-page/',
    livePreviewLink: 'https://abdul-rehman-d.github.io/frontend_mentor_challenges/14_ping-coming-soon-page/',
    technologies: ['HTML', 'CSS'],
    type: ['ui-implementation'],
  },
  {
    id: 3,
    title: 'Single Price Grid Component',
    description: 'A three section grid system with complex layout, varying over screen sizes.',
    thumbnail: 'https://github.com/abdul-rehman-d/frontend_mentor_challenges/raw/main/assets/13.jpg',
    sourceCodeLink: 'https://github.com/abdul-rehman-d/frontend_mentor_challenges/tree/main/15_huddle-landing-page-with-single-introductory-section/',
    livePreviewLink: 'https://abdul-rehman-d.github.io/frontend_mentor_challenges/15_huddle-landing-page-with-single-introductory-section/',
    technologies: ['HTML', 'CSS'],
    type: ['ui-implementation'],
  },
  {
    id: 4,
    title: 'Intro Component With Signup Form',
    description: 'A responsive hero section with a complete form validation with different fields with different error messages and responses.',
    thumbnail: 'https://github.com/abdul-rehman-d/frontend_mentor_challenges/raw/main/assets/12.jpg',
    sourceCodeLink: 'https://github.com/abdul-rehman-d/frontend_mentor_challenges/tree/main/12_intro-component-with-signup-form/',
    livePreviewLink: 'https://abdul-rehman-d.github.io/frontend_mentor_challenges/12_intro-component-with-signup-form/',
    technologies: ['HTML', 'CSS', 'Javascript'],
    type: ['featured', 'ui-implementation'],
  },
  {
    id: 5,
    title: 'Base Apparel Coming Soon',
    description: 'A coming soon three section webpage with complete form validation and mobile friendly design.',
    sourceCodeLink: 'https://github.com/abdul-rehman-d/frontend_mentor_challenges/tree/main/11_base-apparel-coming-soon/',
    thumbnail: 'https://github.com/abdul-rehman-d/frontend_mentor_challenges/raw/main/assets/11.jpg',
    livePreviewLink: 'https://abdul-rehman-d.github.io/frontend_mentor_challenges/11_base-apparel-coming-soon/',
    technologies: ['HTML', 'CSS', 'Javascript'],
    type: ['ui-implementation'],
  }
]

export default projects